# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 550)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_addWin = QtWidgets.QPushButton(self.widget)
        self.pushButton_addWin.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_addWin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_addWin.setObjectName("pushButton_addWin")
        self.horizontalLayout.addWidget(self.pushButton_addWin)
        self.pushButton_delWin = QtWidgets.QPushButton(self.widget)
        self.pushButton_delWin.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_delWin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_delWin.setObjectName("pushButton_delWin")
        self.horizontalLayout.addWidget(self.pushButton_delWin)
        self.pushButton_queryWin = QtWidgets.QPushButton(self.widget)
        self.pushButton_queryWin.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_queryWin.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_queryWin.setObjectName("pushButton_queryWin")
        self.horizontalLayout.addWidget(self.pushButton_queryWin)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_1_count = QtWidgets.QLabel(self.widget)
        self.label_1_count.setObjectName("label_1_count")
        self.horizontalLayout.addWidget(self.label_1_count)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_1_bit = QtWidgets.QLabel(self.widget)
        self.label_1_bit.setObjectName("label_1_bit")
        self.horizontalLayout.addWidget(self.label_1_bit)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_2_count = QtWidgets.QLabel(self.widget)
        self.label_2_count.setObjectName("label_2_count")
        self.horizontalLayout.addWidget(self.label_2_count)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_2_bit = QtWidgets.QLabel(self.widget)
        self.label_2_bit.setObjectName("label_2_bit")
        self.horizontalLayout.addWidget(self.label_2_bit)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.label_3_count = QtWidgets.QLabel(self.widget)
        self.label_3_count.setObjectName("label_3_count")
        self.horizontalLayout.addWidget(self.label_3_count)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_3_bit = QtWidgets.QLabel(self.widget)
        self.label_3_bit.setObjectName("label_3_bit")
        self.horizontalLayout.addWidget(self.label_3_bit)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget_1 = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_1.setObjectName("tableWidget_1")
        self.tableWidget_1.setColumnCount(2)
        self.tableWidget_1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_1.setHorizontalHeaderItem(1, item)
        self.tableWidget_1.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_1.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableWidget_1)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.tableWidget_3)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "黑羽的布隆进化器"))
        self.pushButton_addWin.setText(_translate("Form", "增"))
        self.pushButton_delWin.setText(_translate("Form", "删"))
        self.pushButton_queryWin.setText(_translate("Form", "查"))
        self.label.setText(_translate("Form", "原数据条数："))
        self.label_1_count.setText(_translate("Form", "000000"))
        self.label_4.setText(_translate("Form", "占空间："))
        self.label_1_bit.setText(_translate("Form", "000000"))
        self.label_7.setText(_translate("Form", "原布隆条数："))
        self.label_2_count.setText(_translate("Form", "000000"))
        self.label_9.setText(_translate("Form", "占空间："))
        self.label_2_bit.setText(_translate("Form", "000000"))
        self.label_11.setText(_translate("Form", "新布隆条数："))
        self.label_3_count.setText(_translate("Form", "000000"))
        self.label_10.setText(_translate("Form", "占空间："))
        self.label_3_bit.setText(_translate("Form", "000000"))
        self.groupBox.setTitle(_translate("Form", "原数据"))
        item = self.tableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "data"))
        item = self.tableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "count"))
        self.groupBox_2.setTitle(_translate("Form", "原布隆"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "data"))
        self.groupBox_3.setTitle(_translate("Form", "进化布隆"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "data"))
