# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_query.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(876, 601)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_path = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_path.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_path.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_path.setObjectName("pushButton_path")
        self.horizontalLayout_2.addWidget(self.pushButton_path)
        self.lineEdit_path = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_path)
        self.pushButton_many = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_many.setObjectName("pushButton_many")
        self.horizontalLayout_2.addWidget(self.pushButton_many)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_data = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.horizontalLayout_3.addWidget(self.lineEdit_data)
        self.pushButton_one = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_one.setObjectName("pushButton_one")
        self.horizontalLayout_3.addWidget(self.pushButton_one)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_true = QtWidgets.QLabel(self.groupBox_7)
        self.label_true.setObjectName("label_true")
        self.horizontalLayout_4.addWidget(self.label_true)
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_true_bi = QtWidgets.QLabel(self.groupBox_7)
        self.label_true_bi.setObjectName("label_true_bi")
        self.horizontalLayout_4.addWidget(self.label_true_bi)
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_false = QtWidgets.QLabel(self.groupBox_7)
        self.label_false.setObjectName("label_false")
        self.horizontalLayout_4.addWidget(self.label_false)
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_false_bi = QtWidgets.QLabel(self.groupBox_7)
        self.label_false_bi.setObjectName("label_false_bi")
        self.horizontalLayout_4.addWidget(self.label_false_bi)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.groupBox_8)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.label_true_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_true_2.setObjectName("label_true_2")
        self.horizontalLayout_11.addWidget(self.label_true_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.label_true_bi_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_true_bi_2.setObjectName("label_true_bi_2")
        self.horizontalLayout_11.addWidget(self.label_true_bi_2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.label_false_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_false_2.setObjectName("label_false_2")
        self.horizontalLayout_11.addWidget(self.label_false_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.label_false_bi_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_false_bi_2.setObjectName("label_false_bi_2")
        self.horizontalLayout_11.addWidget(self.label_false_bi_2)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_6.addWidget(self.tableWidget)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_5.addWidget(self.tableWidget_2)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.groupBox_6)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_3.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_9.addWidget(self.tableWidget_3)
        self.horizontalLayout_10.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_5)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_8.addWidget(self.tableWidget_4)
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "查询"))
        self.pushButton_path.setText(_translate("Dialog", "路径"))
        self.pushButton_many.setText(_translate("Dialog", "查询多条"))
        self.label.setText(_translate("Dialog", "数据"))
        self.pushButton_one.setText(_translate("Dialog", "查询一条"))
        self.groupBox_7.setTitle(_translate("Dialog", "原布隆"))
        self.label_2.setText(_translate("Dialog", "查询成功"))
        self.label_true.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "查询成功率"))
        self.label_true_bi.setText(_translate("Dialog", "0"))
        self.label_4.setText(_translate("Dialog", "查询失败"))
        self.label_false.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "查询失败率"))
        self.label_false_bi.setText(_translate("Dialog", "0"))
        self.groupBox_8.setTitle(_translate("Dialog", "新布隆"))
        self.label_3.setText(_translate("Dialog", "查询成功"))
        self.label_true_2.setText(_translate("Dialog", "0"))
        self.label_7.setText(_translate("Dialog", "查询成功率"))
        self.label_true_bi_2.setText(_translate("Dialog", "0"))
        self.label_8.setText(_translate("Dialog", "查询失败"))
        self.label_false_2.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "查询失败率"))
        self.label_false_bi_2.setText(_translate("Dialog", "0"))
        self.groupBox.setTitle(_translate("Dialog", "原布隆"))
        self.groupBox_4.setTitle(_translate("Dialog", "成功"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "data"))
        self.groupBox_3.setTitle(_translate("Dialog", "失败"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "data"))
        self.groupBox_2.setTitle(_translate("Dialog", "新布隆"))
        self.groupBox_6.setTitle(_translate("Dialog", "成功"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "data"))
        self.groupBox_5.setTitle(_translate("Dialog", "失败"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "data"))
